import os


def load_text(args):
    if args.dataset == 'FashionAI':
        true_label = [
            ["an invisible length skirt", "a short length skirt", "a knee length skirt", "a midi length skirt", "an ankle length skirt", "a floor length skirt"],
            ["invisible length sleeves", "sleeveless sleeves", "cup sleeves", "short sleeves", "elbow sleeves",
             "3/4 sleeves", "wrist length sleeves", "long sleeves", "extra long sleeves"],
            ["an invisible length coat", "a high waist length coat", "a regular length coat", "a long length coat", "a micro length coat", "a knee length coat", "a midi length coat", "an ankle&floor length coat"],
            ["an invisible length pant", "a short pant", "a mid length pant", "a 3/4 length pant", "a cropped pant",
             "a full length pant"],
            ["an invisible collar design", "a shirt collar", "a peter pan collar", "a puritan collar", "a rib collar"],
            ["an invisible lapel design", "a notched lapel", "a collarless lapel", "a shawl collar", "a plus size shawl"],
            ["an invisible neckline design", "a strapless neck", "a deep v neckline", "a straight neck", "a v neckline",
             "a square neckline", "an off shoulder", "a round neckline", "a sweat heart neck", "a one shoulder neckline"],
            ["an invisible neck design", "a turtle neck", "a ruffle semi-high collar", "a low turtle neck", "a draped collar"],
        ]
        prompt = ["a photo of ", "a fashion with ", "a fashion with ",
                  "a fashion with ", "a fashion with ", "a fashion with ",
                  "a fashion with ", "a fashion with "]


    elif args.dataset == 'DeepFashion':
        true_label = [
            ['abstract', 'abstract chevron', 'abstract chevron print', 'abstract diamond', 'abstract floral',
             'abstract floral print', 'abstract geo', 'abstract geo print', 'abstract paisley', 'abstract pattern',
             'abstract print', 'abstract printed', 'abstract stripe', 'animal', 'animal print', 'bandana',
             'bandana print', 'baroque', 'baroque print', 'bird', 'bird print', 'botanical', 'botanical print',
             'boxy striped', 'breton', 'breton stripe', 'brushstroke', 'brushstroke print', 'butterfly',
             'butterfly print', 'camo', 'camouflage', 'checked', 'checkered', 'cheetah', 'chevron', 'chevron print',
             'chiffon floral', 'circle', 'clashist', 'classic striped', 'colorblock', 'colorblocked', 'crochet floral',
             'daisy', 'daisy print', 'diamond', 'diamond print', 'ditsy', 'ditsy floral', 'ditsy floral print', 'dot',
             'dots', 'dotted', 'embroidered floral', 'floral', 'floral flutter', 'floral paisley', 'floral pattern',
             'floral print', 'floral textured', 'floral-embroidered', 'flower', 'foil', 'folk', 'folk print', 'geo',
             'geo pattern', 'geo print', 'geo stripe', 'giraffe', 'giraffe print', 'graphic', 'grid', 'grid print',
             'heart', 'heart print', 'heathered stripe', 'houndstooth', 'ikat', 'ikat print', 'kaleidoscope',
             'kaleidoscope print', 'knit stripe', 'knit striped', 'leaf', 'leaf print', 'leave', 'leopard',
             'leopard print', 'linen', 'linen-blend', 'mandala', 'mandala print', 'marble', 'marble print', 'marled',
             'marled stripe', 'medallion', 'medallion print', 'mixed', 'mixed print', 'mixed stripe', 'mosaic',
             'mosaic print', 'multi-stripe', 'nautical', 'nautical stripe', 'nautical striped', 'ombre', 'ornate',
             'ornate paisley', 'ornate print', 'paint', 'paint splatter', 'painted', 'paisley', 'paisley print', 'palm',
             'palm print', 'palm springs', 'palm tree', 'pattern', 'patterned', 'pinstripe', 'pinstriped', 'polka dot',
             'pom-pom', 'print', 'print shirt', 'print woven', 'printed', 'ribbed stripe', 'ringer', 'rugby stripe',
             'rugby striped', 'sophisticated', 'southwestern', 'southwestern-inspired', 'southwestern-patterned',
             'southwestern-print', 'speckled', 'splatter', 'spotted', 'stripe', 'striped', 'stripes', 'structured',
             'tonal', 'tribal', 'tribal-inspired', 'two-tone', 'varsity-striped', 'watercolor', 'zig', 'zigzag'],

            ['acid', 'acid wash', 'applique', 'bead', 'beaded', 'beaded chiffon', 'beaded sheer', 'bejeweled', 'bleach',
             'bleached', 'bleached denim', 'brocade', 'burnout', 'cable', 'cable knit', 'cable-knit', 'canvas',
             'chambray', 'chambray drawstring', 'chenille', 'chiffon', 'chiffon lace', 'chiffon layered',
             'chiffon shirt', 'chino', 'chunky', 'chunky knit', 'classic cotton', 'classic denim', 'classic knit',
             'classic woven', 'clean', 'clean wash', 'cloud', 'cloud wash', 'coated', 'corduroy', 'cotton',
             'cotton drawstring', 'cotton knit', 'cotton-blend', 'crepe', 'crepe woven', 'crinkled', 'crochet',
             'crochet embroidered', 'crochet knit', 'crochet lace', 'crochet mesh', 'crochet overlay', 'crocheted',
             'crocheted lace', 'cuffed denim', 'cutout lace', 'damask', 'denim', 'denim drawstring', 'denim shirt',
             'denim utility', 'dip-dye', 'dip-dyed', 'distressed', 'dye', 'elasticized', 'embellished', 'embroidered',
             'embroidered gauze', 'embroidered lace', 'embroidered mesh', 'embroidered woven', 'embroidery', 'eyelash',
             'eyelash knit', 'eyelash lace', 'eyelet', 'faded', 'fair', 'fair isle', 'faux', 'faux fur', 'faux leather',
             'faux shearling', 'faux suede', 'feather', 'floral knit', 'floral lace', 'floral mesh', 'foulard',
             'frayed', 'french', 'french terry', 'fur', 'fuzzy', 'fuzzy knit', 'gauze', 'gauzy', 'gem', 'georgette',
             'gingham', 'glass', 'glitter', 'heathered', 'heathered knit', 'herringbone', 'jacquard', 'knit',
             'knit lace', 'lace', 'lace layered', 'lace mesh', 'lace overlay', 'lace panel', 'lace paneled',
             'lace pleated', 'lace print', 'lace sheer', 'lace-paneled', 'lacy', 'lattice', 'layered', 'leather',
             'leather paneled', 'leather quilted', 'leather-paneled', 'led', 'loop', 'loose', 'loose-knit', 'mesh',
             'mesh overlay', 'mesh panel', 'mesh paneled', 'mesh-paneled', 'metallic', 'mineral', 'mineral wash',
             'neon', 'neoprene', 'nets', 'netted', 'nylon', 'oil', 'organza', 'origami', 'overlay', 'panel', 'paneled',
             'patched', 'patchwork', 'perforated', 'pima', 'pintuck', 'pintuck pleated', 'pintucked', 'plaid',
             'plaid shirt', 'pleat', 'pleated', 'pleated woven', 'pointelle', 'ponte', 'print satin', 'print scuba',
             'purl', 'quilted', 'rhinestone', 'rib', 'rib-knit', 'ribbed', 'ribbed-knit', 'ripped', 'ruched', 'ruffle',
             'ruffled', 'sateen', 'satin', 'scuba', 'seam', 'seamless', 'seersucker', 'semi-sheer', 'sequin',
             'sequined', 'shaggy', 'shearling', 'sheer', 'sheer-paneled', 'shirred', 'shredded', 'sleek', 'slick',
             'slub', 'slub-knit', 'sparkling', 'stone', 'stone washed', 'stones', 'stretch', 'stretch-knit', 'studded',
             'suede', 'tapestry', 'tartan', 'terry', 'textured', 'textured woven', 'tie-dye', 'tiered', 'tile', 'tulle',
             'tweed', 'twill', 'velvet', 'velveteen', 'waffle', 'wash', 'washed', 'woven'],

            ['a-line', 'ankle', 'asymmetric', 'asymmetrical', 'baja', 'bandage', 'beaded shift', 'bermuda', 'bib',
             'big', 'bodycon', 'bodycon midi', 'box', 'box pleat', 'box-pleated', 'boxy', 'boxy crop', 'boxy knit',
             'boxy lace', 'bustier', 'caged', 'cami', 'cami crop', 'cami maxi', 'capri', 'cargo', 'chiffon maxi',
             'chiffon paneled', 'chiffon pleated', 'chiffon shift', 'chiffon-paneled', 'classic fit', 'classic skinny',
             'combo', 'combo maxi', 'cover-up', 'cozy', 'crepe shift', 'crochet crop', 'crochet maxi',
             'crochet-paneled', 'crop', 'cropped', 'cropped knit', 'cut', 'cutoff', 'cutout', 'cutout maxi',
             'cutout sheath', 'denim pencil', 'denim shift', 'denim skater', 'distressed low-rise',
             'distressed mid-rise', 'distressed skinny', 'drapey', 'embroidered fit', 'embroidered gauze peasant',
             'embroidered maxi', 'embroidered peasant', 'embroidered shift', 'eyelet fit', 'faux leather mini',
             'faux leather moto', 'faux leather paneled', 'faux leather pencil', 'faux leather skater',
             'faux leather varsity', 'faux leather-paneled', 'faux-wrap', 'fit', 'fit flare', 'fit skinny', 'fitted',
             'flare', 'flared', 'floral lace mini', 'floral lace sheath', 'floral lace skater', 'floral maxi',
             'floral midi', 'floral mini', 'floral peasant', 'floral pleated', 'floral print skater', 'floral shift',
             'floral skater', 'flounce maxi', 'flowy', 'fold-over', 'foldover', 'gaucho', 'gauze maxi', 'gauze peasant',
             'graphic muscle', 'harem', 'high-low', 'high-rise', 'high-rise skinny', 'knee-length', 'knit longline',
             'knit maxi', 'knit mini', 'knit pencil', 'knit skater', 'knit trapeze', 'kurt', 'lace maxi', 'lace midi',
             'lace mini', 'lace pencil', 'lace sheath', 'lace shift', 'lace skater', 'leather mini', 'leather moto',
             'leather pencil', 'leather skater', 'leather varsity', 'longline', 'longline shirt', 'low-rise',
             'low-rise skinny', 'maxi', 'medium', 'mid rise', 'mid rise skinny', 'mid-rise', 'mid-rise skinny', 'midi',
             'mini', 'moto', 'muscle', 'overlay sheath', 'oversized', 'peasant', 'pencil', 'pleated skater', 'polo',
             'popover', 'print shift', 'print skater', 'print smock', 'print smocked', 'print tulip', 'puffer',
             'pullover', 'raw', 'raw-cut', 'rise', 'rise skinny', 'rose skater', 'round', 'scuba skater', 'sheath',
             'shift', 'shirt', 'skater', 'skinny', 'skinny stretch', 'skort', 'slim', 'slip', 'slouchy', 'smock',
             'smocked', 'square', 'straight-leg', 'striped trapeze', 'swing', 'trapeze', 'trouser', 'tube', 'tulip',
             'tunic', 'vertical', 'wide-leg', 'windbreaker', 'windowpane', 'wrap'],

            ['arrow collar', 'asymmetrical hem', 'back bow', 'back cutout', 'back knit', 'back lace', 'back striped',
             'backless', 'batwing', 'beaded collar', 'bell', 'bell-sleeve', 'belted', 'belted chiffon', 'belted floral',
             'belted floral print', 'belted lace', 'belted maxi', 'belted plaid', 'boat neck', 'bow', 'bow-back',
             'bow-front', 'boxy pocket', 'braided', 'button', 'button-front', 'buttoned', 'cap-sleeve',
             'chiffon surplice', 'cinched', 'classic crew', 'classic crew neck', 'classic pocket', 'classic v-neck',
             'collar', 'collar lace', 'collared', 'collarless', 'collarless faux', 'colorblock pocket', 'contrast',
             'contrast trim', 'contrast-trimmed', 'convertible', 'cowl', 'cowl neck', 'crew', 'crew neck', 'crisscross',
             'crisscross-back', 'crochet fringe', 'crochet-trimmed', 'cross-back', 'crossback', 'cuffed',
             'cuffed-sleeve', 'curved', 'curved hem', 'cutout-back', 'deep v-neck', 'deep-v', 'dolman', 'dolman sleeve',
             'dolman-sleeve', 'dolphin', 'dolphin hem', 'double-breasted', 'drape-front', 'draped', 'draped open-front',
             'draped shawl', 'draped surplice', 'drawstring', 'drop waist', 'drop-sleeve', 'drop-waist', 'dropped',
             'elephant', 'elephant print', 'faux leather-trimmed', 'fitted v-neck', 'flat', 'flat front', 'flat-front',
             'floral print strapless', 'floral print surplice', 'floral surplice', 'flounce', 'flounced', 'fluted',
             'flutter', 'flutter sleeve', 'flutter-sleeve', 'fringe', 'fringed', 'gathered waistline',
             'graphic racerback', 'heathered v-neck', 'hem', 'high-neck', 'high-slit', 'high-slit maxi', 'high-waist',
             'high-waisted', 'hood', 'hooded', 'hooded maxi', 'hooded utility', 'illusion', 'illusion neckline',
             'kangaroo', 'kangaroo pocket', 'keyhole', 'knit open', 'knit pocket', 'knit raglan', 'knit shawl',
             'knit v-neck', 'knotted', 'lace peplum', 'lace sleeve', 'lace trim', 'lace-trim', 'lace-trimmed',
             'lace-up', 'ladder-back', 'lapel', 'leather peplum', 'leather trimmed', 'leather-trimmed', 'long sleeve',
             'long-sleeve', 'long-sleeved', 'm-slit', 'm-slit maxi', 'mesh racerback', 'mesh-trimmed', 'mock',
             'mock neck', 'mock-neck', 'neck ribbed', 'neck skater', 'neck striped', 'neckline', 'notched collar',
             'off-the-shoulder', 'one-button', 'one-shoulder', 'open-back', 'open-front', 'open-knit', 'open-shoulder',
             'peplum', 'pin', 'pocket', 'print racerback', 'print strapless', 'print strappy', 'print surplice',
             'print v-neck', 'racerback', 'raglan', 'raglan sleeve', 'ruffle trim', 'scallop', 'scalloped', 'scoop',
             'scoop-neck', 'self-tie', 'shawl', 'shoulder', 'side slit', 'side-slit', 'single-button', 'sleeve',
             'sleeveless', 'slit', 'split', 'split-back', 'split-neck', 'strap', 'strapless', 'strapless tribal',
             'strappy', 'striped v-neck', 'surplice', 'suspender', 't-back', 'tassel', 'tasseled', 'tie-back',
             'tie-front', 'tie-neck', 'toggle', 'topstitched', 'trim', 'trimmed', 'tulip-back', 'turtle-neck',
             'twist-front', 'twisted', 'two-button', 'v-back', 'v-cut', 'v-neck', 'vent', 'vented hem', 'y-back', 'zip',
             'zip-front', 'zip-pocket', 'zip-up', 'zipped', 'zipper', 'zippered'],

            ['americana', 'angeles', 'art', 'athletic', 'audrey', 'babe', 'babydoll', 'barbie', 'baseball', 'basic',
             'basquiat', 'beach', 'beatles', 'bed', 'bella', 'bike', 'biker', 'blah', 'blurred', 'boho', 'bold',
             'boyfriend', 'brooklyn', 'brooklyn nets', 'california', 'camera', 'candy', 'cardio', 'cat', 'chic',
             'cities', 'city', 'civil', 'classic', 'coast', 'coffee', 'cute', 'dainty', 'daring', 'dark', 'darling',
             'defyant', 'desert', 'destroyed', 'devil', 'doll', 'doodle', 'dream', 'dreamcatcher', 'dreamer',
             'dynamite', 'eagle', 'edge', 'eiffel', 'elegant', 'enchanted', 'ethereal', 'everyday', 'fan', 'fancy',
             'festive', 'field', 'fisherman', 'flawless', 'flirty', 'floyd', 'fox', 'france', 'free spirit', 'fresh',
             'frida', 'galaxy', 'garden', 'garden party', 'genuine', 'girl', 'girls', 'grunge', 'guns', 'halen', 'heat',
             'hepburn', 'heroes', 'inset', 'internet', 'island', 'isle', 'joie', 'kahlo', 'kid', 'killin', 'kiss',
             'kitty', 'la', 'lady', 'lakers', 'laser', 'life', 'light', 'lightning', 'logo', 'lounge', 'love', 'lover',
             'loyal', 'luxe', 'mandarin', 'map', 'marilyn', 'marilyn monroe', 'matelot', 'meow', 'miami', 'mickey',
             'mickey mouse', 'mina', 'minnie', 'minnie mouse', 'mirrored', 'mob', 'mod', 'modernist', 'monroe', 'moon',
             'morning', 'muse', 'new york', 'night', 'notorious', 'ny', 'nyc', 'oxford', 'pan', 'paradise', 'paris',
             'party', 'performance', 'pineapple', 'pink', 'pizza', 'pj', 'please', 'popcorn', 'posh', 'power', 'quirky',
             'rad', 'raga', 'rainbow', 'rebel', 'red', 'refined', 'regime', 'relaxed', 'retro', 'reverse', 'reversible',
             'roll', 'rolling', 'rolling stones', 'roman', 'rose', 'roses', 'rugby', 'run', 'running', 'rustic',
             'safari', 'sea', 'seaside', 'shark', 'shopping', 'shore', 'sky', 'smart', 'smile', 'snap', 'snoopy',
             'soft', 'solid', 'spirit', 'spongebob', 'sporty', 'springs', 'standout', 'star', 'stars', 'studio',
             'summer', 'sun', 'sunburst', 'sunflower', 'surfer', 'sweet', 'sweetheart', 'swim', 'swiss', 'taco',
             'tasmanian', 'texas', 'thermal', 'tokyo', 'tower', 'track', 'training', 'tree', 'trench', 'triangle',
             'tropical', 'trouble', 'tupac', 'utility', 'van', 'varsity', 'venice', 'voyager', 'wake', 'wave',
             'weekend', 'west', 'wifey', 'wild', 'wildflower', 'woke', 'workout', 'yoga', 'yoke', 'york', 'youth',
             'zeppelin']

        ]
        prompt = ['a fashion with a texture of ', 'a fashion with a fabric of ', 'a fashion with a shape of ',
                  'a fashion with a part of ', 'a fashion with a style of ']

        gpt_labels = [
         ["smooth", "rough", "silky", "velvety", "grainy", "bumpy", "fuzzy", "soft", "coarse", "textured", "polished",
          "matte", "glossy", "shiny", "satin-like", "woven", "embellished", "embroidered", "fluffy", "sheer", "lacey",
          "ribbed", "pleated", "crinkled", "frosted", "distressed", "weathered", "sparkling", "glittery", "glimmering",
          "luxurious", "elegant", "ornate", "ornamental", "baroque", "rustic", "vintage", "gritty", "delicate",
          "intricate", "smooth-to-the-touch", "textured-to-perfection", "matte-finish", "high-gloss", "fuzzy-finish",
          "heavy-duty", "soft-touch", "pebbled", "canvas-like", "embroidered", "fringed", "knitted", "crocheted",
          "tight-knit", "loose-knit", "structured", "fluid", "cloud-like", "slick", "furry", "cozy", "snug", "plush",
          "velvety-smooth", "sandpaper-like", "suede", "nubuck", "grippy", "twilled", "crinkled", "slubbed",
          "grainy-texture", "soft-grip", "scuffed", "weathered-leather", "textured-leather", "crinkly",
          "pleated-finish", "waterproof", "thick-threaded", "gossamer", "translucent", "woven-texture", "frayed",
          "tightly-woven", "loose-woven", "threadbare", "matted", "dense-weave", "open-weave", "honeycomb", "cut-out",
          "quilted", "pleated-texture", "smooth-leather", "grain-leather", "burnished"],
         ["denim", "jean fabric", "denim cloth", "cotton fabric", "silk", "silk material", "cotton weave",
          "woolen fabric", "linen", "linen fabric", "knitted fabric", "polyester blend", "spandex material", "velvet",
          "velvet fabric", "suede", "leather", "faux leather", "tweed fabric", "corduroy", "cashmere", "cashmere wool",
          "nylon", "satin", "satin cloth", "chiffon", "chiffon fabric", "lace", "lace fabric", "jersey",
          "jersey material", "organza", "organza fabric", "brocade", "brocade fabric", "canvas", "canvas material",
          "gabardine", "gabardine fabric", "herringbone fabric", "flannel", "flannel cloth", "tulle", "tulle fabric",
          "fleece", "fleece material", "moleskin fabric", "microfiber", "acrylic fabric", "rayon", "rayon material",
          "georgette", "georgette fabric", "plaid fabric", "quilted fabric", "crepe fabric", "denim weave",
          "polyester satin", "denim weave", "tartan fabric", "bamboo fabric", "ribbed fabric", "stretch denim",
          "performance fabric", "ribbed knit", "poplin", "poplin fabric", "tencel", "tencel fabric", "denim blend",
          "t-shirt fabric", "polyester cotton blend", "stretch fabric", "denim twill", "boiled wool",
          "herringbone weave", "leatherette", "stretch knit fabric", "jersey knit", "performance knit",
          "double knit fabric", "sweater knit", "minky fabric", "faux fur", "faux suede", "vintage cotton",
          "terrycloth", "towel fabric", "ribbed cotton", "faux wool", "silk chiffon", "wool blend", "crepe de chine",
          "seersucker fabric", "sandwashed silk", "velour fabric", "metallic fabric", "space fabric",
          "reflective fabric", "tinsel fabric", "teddy fabric", "denim chambray", "faux leatherette", "washed cotton",
          "woven cotton", "stretch velvet", "coated denim", "lightweight knit", "thermal fabric", "sweatshirt fabric",
          "bubble fabric", "stretch satin", "stretch lace", "glitter fabric", "flocked fabric", "terry fabric",
          "mock leather", "crêpe material", "interlock fabric", "waxed cotton", "stretch linen", "peacoat wool",
          "vintage velvet", "faux cashmere", "neoprene fabric", "tartan weave", "boiled wool fabric",
          "waterproof fabric", "tech fabric", "woven wool", "hounds-tooth fabric", "floral lace", "patterned silk"],
         ["A-line", "fit-and-flare", "flared", "boxy", "tailored", "oversized", "slim-fit", "cropped", "draped",
          "fitted", "loose", "bodycon", "peplum", "pleated", "structured", "voluminous", "straight-leg", "high-waisted",
          "low-rise", "asymmetrical", "wrap-around", "empire waist", "high-neck", "V-neck", "square-neck", "cowl-neck",
          "strapless", "off-shoulder", "halter", "tunic", "pencil skirt", "A-line skirt", "maxi", "mini", "midi",
          "knee-length", "body-hugging", "flounce", "tapered", "drop-waist", "cap-sleeve", "three-quarter sleeve",
          "long-sleeve", "batwing", "raglan", "puffer", "peacoat", "trench", "double-breasted", "single-breasted",
          "denim", "cargo", "balloon sleeves", "high-low hem", "tiered", "ruffled", "capri", "culottes", "wide-leg",
          "bootcut", "flare-leg", "straight-cut", "jumpsuit", "romper", "shift dress", "shift tunic", "wrap dress",
          "T-shirt dress", "maxi dress", "sheath dress", "smock dress", "sweater dress", "pencil dress", "co-ord",
          "blouson", "skater", "peasant blouse", "off-the-shoulder", "kimono-style", "poufy", "funnel-neck",
          "halter-neck", "bolero", "waisted", "drop-shoulder", "v-neckline", "cut-out", "high-low dress",
          "flare-bottom", "pleat-front", "belted", "notch-collar", "collared", "V-shaped", "round-neck", "square-cut",
          "double-waist", "wrap-around skirt", "flutter sleeve", "mock-neck", "seamless", "distressed",
          "tailored trousers", "pencil pant", "bootcut jeans", "flare jeans", "tapered jeans", "skinny jeans",
          "mom jeans", "boyfriend jeans", "straight-leg jeans", "paperbag waist", "jeggings", "leggings", "chinos",
          "joggers", "tartan", "checked", "striped", "printed", "pleat-front", "smocking", "peplum waist",
          "A-line coat", "duster coat", "cardigan", "puffer jacket", "bomber jacket", "duffle coat", "blazer",
          "longline blazer", "pea coat", "parka", "windbreaker", "sweatshirt", "crew-neck sweater", "cardigan",
          "hoodie", "wrap-around coat", "draped jacket", "chambray shirt", "overshirt", "puffer vest", "track pants",
          "blouse", "bodysuit", "flannel shirt", "sweater vest", "bustier", "bralette", "halter top", "crop top",
          "tank top", "mock neck top", "camisole", "peasant top", "v-neck sweater", "crew-neck sweater",
          "sweatshirt dress", "long-sleeve shirt", "double-layered dress", "bandeau", "muscle tee", "off-shoulder top",
          "sash belt", "sweater cardigan", "kimono top", "tunic dress", "pinafore", "shift tunic", "shirt dress",
          "cape coat", "bustle skirt", "bubble hem", "capri pants", "sailor pants", "denim jacket", "peacoat jacket",
          "chore coat", "waffle-knit", "flared jeans", "distressed jeans", "studded", "frayed hem", "cargo shorts",
          "athletic shorts", "mini skirt", "trouser skirt", "skort", "leather pants", "linen trousers", "sweater skirt",
          "pleated trousers", "double-layered skirt", "sheer overlay", "quilted jacket", "faux fur coat",
          "windbreaker jacket", "capelet", "serape", "utility jacket", "tailored blazer", "pinstripe", "harem pants",
          "denim overalls", "maxi skirt", "cowl-back top", "peasant blouse", "batwing sleeve dress", "bomber jacket",
          "blazer dress", "tuxedo dress", "halter-neck dress", "puffer vest"],
         ["arrow collar", "wing collar", "stand-up collar", "high-neck collar", "mandarin collar", "shawl collar",
          "notch collar", "peaked collar", "bow collar", "placket", "button placket", "zippered closure", "v-neck",
          "crew neck", "scoop neck", "boat neck", "turtleneck", "mock neck", "keyhole neckline", "halter neck",
          "collarless", "cap sleeves", "raglan sleeves", "batwing sleeves", "puff sleeves", "bell sleeves",
          "three-quarter sleeves", "short sleeves", "long sleeves", "flare sleeves", "slit sleeves", "bell-bottoms",
          "bootcut jeans", "skinny jeans", "straight-leg jeans", "high-waisted pants", "low-rise pants", "cargo pants",
          "wide-leg trousers", "chinos", "overalls", "culottes", "pleated skirt", "A-line skirt", "pencil skirt",
          "mini skirt", "midi skirt", "maxi skirt", "wrap skirt", "bodycon dress", "shift dress", "sheath dress",
          "empire waist dress", "tea-length dress", "sundress", "halter dress", "peplum top", "crop top",
          "button-down shirt", "oxford shirt", "blouse", "chambray shirt", "tunic", "v-neck sweater",
          "crew neck sweater", "cardigan", "hoodie", "blazer", "bomber jacket", "denim jacket", "peacoat",
          "trench coat", "puffer jacket", "fur coat", "parka", "raincoat", "windbreaker", "leather jacket",
          "blouson jacket", "utility jacket", "sports bra", "bralette", "lace bra", "underwired bra",
          "high-waisted briefs", "boyshorts", "thong", "bikini", "swimsuit", "tankini", "sarong", "shawl", "scarf",
          "pashmina", "gloves", "mittens", "beanie", "fedora", "panama hat", "sun hat", "beret", "bucket hat",
          "boater hat", "cowboy boots", "ankle boots", "Chelsea boots", "combat boots", "knee-high boots",
          "over-the-knee boots", "loafer shoes", "oxford shoes", "ballet flats", "espadrilles", "sandals", "flip-flops",
          "high heels", "platform shoes", "wedges", "stilettos", "mules", "clogs", "slip-ons", "sneakers", "trainers",
          "running shoes", "combat shoes", "chukka boots", "driving shoes", "loafers", "clutch bag", "crossbody bag",
          "shoulder bag", "tote bag", "hobo bag", "backpack", "satchel", "briefcase", "fanny pack", "weekender bag",
          "messenger bag", "wallet", "cardholder", "belt", "waist belt", "skinny belt", "wide belt", "sash", "bracelet",
          "bangle", "watch", "necklace", "choker", "pendant", "earrings", "stud earrings", "hoop earrings",
          "dangly earrings", "brooch", "hairpin", "headband", "barrette", "hair tie", "sunglasses", "reading glasses",
          "spectacles", "optical frames", "socks", "stockings", "tights", "hosiery", "knee-high socks", "ankle socks",
          "leggings", "thermal leggings", "fleece tights", "wool socks", "compression socks", "footless tights",
          "gloves", "sunglasses case", "watch band", "jewelry clasp", "belt buckle", "zipper pull", "button hole",
          "button cover", "cuffs", "cufflinks", "pocket square", "lapel pin", "sash belt", "bow tie", "necktie",
          "cravat", "ascot", "braces", "suspenders", "garter belt", "fishnet stockings", "lace trim", "sequins",
          "beading", "embroidery", "applique", "patchwork", "fringes", "ruffles", "pleats", "gathers", "smocking",
          "bias-cut", "gore", "paneling", "boning", "corset", "petticoat", "lining", "hemline", "draping",
          "tulip skirt", "bubble skirt", "peplum skirt", "poodle skirt", "circle skirt", "skater skirt", "flared pants",
          "palazzo pants", "sweater vest", "puffer vest", "cardigan vest", "tunic dress", "denim dress", "shift dress",
          "wrap dress", "midi dress", "maxi dress", "peasant blouse", "gathered waist", "smocked waist",
          "cinched waist", "empire waist", "drop waist", "A-line dress", "halter top", "graphic tee", "striped shirt",
          "checked shirt", "polka dot shirt", "plaid shirt", "denim vest", "zip-up hoodie", "sweatshirt", "polo shirt",
          "thermal top", "sports bra", "compression shorts", "jumpsuit", "romper", "short romper", "long romper",
          "track pants", "baseball cap", "snapback hat", "knitted hat", "beanie hat", "floppy hat", "sun hat",
          "visor hat", "bucket hat", "fedora hat", "trilby hat", "top hat", "cloche hat", "beret hat", "bandana",
          "headscarf", "scrunchie", "hairband", "ponytail holder", "hair clip", "bandana headband", "wrap headband",
          "stretch headband", "ear warmers", "furry earmuffs", "parka coat", "ski jacket", "down jacket", "rain jacket",
          "fur jacket", "peacoat jacket", "trenchcoat jacket", "windbreaker jacket", "puffer jacket", "blouson jacket",
          "denim jacket", "bomber jacket", "leather jacket", "sherpa jacket", "suede jacket", "quilted jacket",
          "lumberjack shirt", "military jacket", "army jacket", "khaki jacket", "oversized coat", "vintage coat",
          "heritage coat", "fashion coat", "puffer coat", "down coat", "utility coat", "coach jacket", "denim vest",
          "bomber vest", "puffer vest", "corduroy vest", "flannel vest", "quilted vest", "chore jacket",
          "faux fur vest", "wool vest", "work jacket", "blazer jacket", "sports jacket", "track jacket", "shirt jacket",
          "rain poncho", "poncho", "cardigan sweater", "knitted sweater", "turtleneck sweater", "hoodie sweatshirt",
          "zip-up sweater", "crewneck sweater", "pullover sweater", "chunky sweater", "fleece jacket",
          "hooded cardigan", "cable-knit sweater", "cashmere sweater", "wool sweater", "alpaca sweater",
          "crochet sweater", "lace sweater", "embroidered sweater", "striped sweater", "printed sweater",
          "fuzzy sweater", "flannel shirt", "plaid flannel", "fleece shirt", "sweatshirt hoodie", "yoga pants",
          "leggings pants", "track pants", "athletic pants", "sweatpants", "sports shorts", "biker shorts",
          "gym shorts", "running shorts", "cargo shorts", "denim shorts", "chino shorts", "pleated shorts", "skort",
          "culotte shorts", "button-down skirt", "flare skirt", "straight skirt", "mini skirt", "long skirt",
          "tulle skirt", "silk skirt", "denim skirt", "leather skirt", "suede skirt", "corduroy skirt", "pencil skirt",
          "satin skirt", "chiffon skirt", "lace skirt", "print skirt", "colorblock skirt", "abstract skirt",
          "floral skirt", "striped skirt", "checkered skirt", "houndstooth skirt", "animal print skirt",
          "pleated pleats", "piped pleats", "knife pleats", "accordion pleats", "gathered pleats", "ruched skirt",
          "smocked skirt", "tiered skirt", "high-low skirt", "wraparound skirt", "slit skirt", "pencil-line skirt",
          "midi skirt", "asymmetrical skirt", "ballerina skirt", "tutu skirt", "maxi skirt", "circle skirt",
          "A-line skirt", "swing skirt", "flared skirt", "peplum skirt", "skater skirt", "plissé skirt", "gathered hem",
          "fluted hem", "scalloped hem", "raw hem", "frayed hem", "cutoff hem", "hem slit", "embroidered hem",
          "lace-trimmed hem", "tassel hem", "fringe hem", "pin-tucked hem", "ruffled hem", "shirred hem",
          "handkerchief hem", "asymmetric hem", "mitered hem", "bias-cut hem"],
         ["casual", "formal", "elegant", "vintage", "bohemian", "minimalist", "chic", "edgy", "preppy", "streetwear",
          "athletic", "sporty", "activewear", "retro", "luxurious", "classic", "sophisticated", "comfortable", "urban",
          "contemporary", "trendy", "bold", "avant-garde", "professional", "romantic", "polished", "laid-back",
          "grunge", "luxury", "eclectic", "feminine", "masculine", "playful", "futuristic", "timeless", "sleek",
          "opulent", "cozy", "refined", "punk", "hip-hop", "boho", "rustic", "street chic", "preppy chic",
          "sports luxe", "ethereal", "androgynous", "high-fashion", "couture", "tailored", "airy", "rebellious",
          "mystical", "glamorous", "bold patterns", "monochromatic", "textured", "functional", "eco-friendly",
          "artisanal", "whimsical", "pastel", "metallic", "neon", "bold color-blocking", "street-inspired",
          "futuristic", "daring", "flirty", "avant-garde", "sporty chic", "mood-based", "subtle elegance",
          "power dressing", "raw", "indie", "tropical", "vibrant", "earthy", "subdued", "natural", "charming",
          "understated", "geometric", "refined", "transitional", "monochrome", "formal chic", "unstructured",
          "unconventional", "utilitarian", "eco-conscious", "sustainable", "athleisure", "relaxed fit",
          "vintage-inspired", "street smart", "soft", "sharp", "futuristic minimalist", "distressed",
          "vibrantly patterned", "neutral", "statement-making", "cool-toned", "richly textured", "understated elegance",
          "functional fashion", "modern minimalist", "artsy", "city chic", "carefree", "romantic vintage",
          "playful chic", "rebelliously elegant", "avant-garde edgy", "boho luxe", "chic casual", "bold stripes",
          "whimsical casual", "sporty elegance", "sleek modern", "bold statement", "romantic and edgy",
          "bold silhouette", "sharp tailoring", "whimsical details", "natural textures", "urban chic",
          "ethereal elegance", "flowy", "trendy comfort", "luxury casual", "structured chic", "bold accessories",
          "soft lines", "artistic fashion", "power casual", "tailored elegance", "luxe streetwear", "oversized",
          "structured silhouette", "timeless classics", "refined elegance", "classic tailoring", "bold cuts",
          "sleek silhouette", "high-tech fashion", "monochrome chic", "clean lines", "earthy tones", "playful patterns",
          "textured fabrics", "modern boho", "abstract patterns", "custom-fit", "eclectic patterns", "gender-neutral",
          "military-inspired", "sporty casual", "seasonal", "minimal chic", "luxury streetwear", "active chic",
          "gothic", "grunge chic", "dark academia", "bright accents", "comfortable luxe", "smart casual",
          "urban casual", "high-end casual", "redefined basics", "statement prints", "sustainable fashion",
          "sport-inspired", "cozy chic", "romantic tailoring", "dynamic chic", "seasonal elegance", "vivid tones",
          "preppy streetwear", "surreal fashion", "indie streetwear", "bold accessories"]
        ]


    else:
        raise NotImplementedError




    return true_label, prompt, gpt_labels



